version: "3.9"

services:
  firewall:
    build: .
    command: python firewall.py
    volumes:
      - .:/app

  gateway:
    build: .
    command: python gateway.py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - firewall
